name: Publish Awesome React

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Print package version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Publishing version: $VERSION"

      - name: Build CLI
        run: npm run build

      - name: Publish to NPM registry
        run: npm publish --provenance --access public
